### ISSUE TITLE
Export fails when trying to bake vcol for subsurfed meshes

### ISSUE THREAD

**Issue by dpogue** [H-uru/korman#266]
If you add a subsurf modifier to a mesh and do **not** apply it, and you try to use the "Bake Lighting" korman modifier and bake to vertex colours, it will silently fail to generate a vcol layer.

If you try to export, it complains about not finding an "autocolor" layer:
```
Traceback (most recent call last):
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/home/dpogue/.config/blender/2.79/scripts/addons/korman/helpers.py", line 58, in __exit__
    self._remove_func(self._obj)
RuntimeError: Error: Vertex color 'autocolor' not found


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/home/dpogue/.config/blender/2.79/scripts/addons/korman/helpers.py", line 58, in __exit__
    self._remove_func(self._obj)
RuntimeError: Error: Vertex color 'autocolor' not found


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dpogue/.config/blender/2.79/scripts/addons/korman/exporter/convert.py", line 130, in run
    self.report.raise_errors()
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/mnt/users/dpogue/Coding/blender-2.79/build/bin/2.79/python/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/home/dpogue/.config/blender/2.79/scripts/addons/korman/helpers.py", line 58, in __exit__
    self._remove_func(self._obj)
RuntimeError: Error: Vertex color 'autocolor' not found
```

This is with korman master (1a60a47ef5f0513db8e6e93c5b208f8cb67605e9)

**Comment by DoobesURU** [comment]
I can confirm I was able to recreate this bug. I slapped a subsurf mod on to a random object...in this case, the Nexus pedestal in the Pub. I made sure there was no VCol layer, then exported. It seems to happen just as the export is about to finish writing the PRP files and complete the Age, if that helps.

**Comment by Jrius** [comment]
Just ran into this too. It happens after export when Korman cleans up meshes, and attempts to remove the autocolor layer it generated. It seems meshes with modifiers cause issues because they require generating a temporary mesh with all modifiers applied, which is deleted _before_ the color layer is removed from the already-deleted mesh. So Blender's API starts acting funny in that case.
If I'm right, the `LightBaker._context_stack` should probably be disposed _before_ the `MeshConverter` in `Exporter.run()` (and probably wherever they appear when used from the modifier itself). I don't know the best way to do this, but I'm sure Hoikas will come to the rescue soon.

**Comment by Hoikas** [comment]
Bah. I was trying to start a system for dealing with some of the undefined behavior in @Deledrius's modifiers, but I guess I will have to move the exit stack into the `_MeshManager` ah well.
