### ISSUE TITLE
Node Trees and Plasma Objects/Pages

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#322]
This one's a very specific and obscure bug, but if an object is part of a modifier such as a node tree, sitting mod, etc. and it's not enabled as a `Plasma Object` _and_ has no Page set, the following error comes up:

```
Traceback (most recent call last):
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\operators\op_export.py", line 228, in execute
    e.run()
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\exporter\convert.py", line 117, in run
    self._export_referenced_node_trees()
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\exporter\convert.py", line 334, in _export_referenced_node_trees
    tree.export(self, bo, so)
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\nodes\node_core.py", line 503, in export
    node.export(exporter, bo, so)
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\nodes\node_conditions.py", line 114, in export
    region.convert_subcondition(exporter, clickable_bo, clickable_so, logicmod)
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\nodes\node_conditions.py", line 184, in convert_subcondition
    region_so = exporter.mgr.find_create_object(plSceneObject, bl=region_bo)
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\exporter\manager.py", line 240, in find_create_object
    key = self.find_key(pClass, bl, name, so)
  File "E:\Program Files (x86)\Blender Foundation\Blender 2.79\2.79\scripts\addons\korman\exporter\manager.py", line 216, in find_key
    location = self._pages[bl.plasma_object.page]
KeyError: ''
```

**Comment by Hoikas** [comment]
Does the Age in question not have a page whose ID is 0?
