### ISSUE TITLE
Korman doesn't support Blender's script reload function

### ISSUE THREAD

**Issue by Deledrius** [H-uru/korman#60]
Blender supports reloading scripts by pressing `F8`, but Korman currently does not work with this feature.  It would useful to have this working for quicker iteration during development.

```
 Exception in module register(): 'Blender\2.78\scripts\addons\korman\__init__.py'
 Traceback (most recent call last):
   File "Blender\2.78\scripts\modules\addon_utils.py", line 350, in enable
     mod.register()
   File "Blender\2.78\scripts\addons\korman\__init__.py", line 38, in register
    bpy.utils.register_module(__name__)
   File "Blender\2.78\scripts\modules\bpy\utils\__init__.py", line 667, in register_module
     raise Exception("register_module(%r): defines no classes" % module)
 Exception: register_module('korman'): defines no classes
```

**Comment by Hoikas** [comment]
Unfortunately, due to Blender's requirement for relative imports in an addon and Python's inability to automatically reload the aforementioned relative imports, this cannot be fixed.
